using System;
using System.Collections.Generic;

namespace TruffleReports.Contracts
{
    /// <summary>
    /// Describes the result of a Report generation.
    /// </summary>
    [Serializable]
    public sealed class ReportGenerationResult
    {
        /// <summary>
        /// Gets or sets fully qualified name of the provider that generated this <see cref="ReportGenerationResult"/>.
        /// </summary>
        public string Provider { get; set; }

        /// <summary>
        /// Gets or sets the messages generated by the provider.
        /// </summary>
        public List<string> Messages { get; set; }

        /// <summary>
        /// Gets or sets the string representation of a <see cref="ReportResult"/> regarding this instance.
        /// </summary>
        public string ReportResult { get; set; }
    }
}